### PR TITLE
Fix automatic component translation 

### PR DESCRIPTION
**Pull request by GreenpixDev**
I removed the "final" modifier from the field "AUTOMATIC_COMPONENT_TRANSLATION" to enable component translation.

### CODE REVIEW

**Comment by kezz** [comment]
Not 100% sure about this one. The reason we kept it final was so a lot of stuff get cleverly compiled away. I really doubt the performance hit from making this non-final is meaningful, however.

**Comment by NukeKM** [comment]
It really doesn't make sense though. Why add automatic component translation in the first place? As far as I know it can't be manually set to true, so even if I'd need to use it, I won't be able to. In my opinion, making it non-final is the best option here. (Sorry for my english)

**Comment by ifxory-plugins** [comment]
Hey, why do you keep this field in class, if in this case, you could be remove it? Meaning from it, if it cannot be changed?

**Comment by Faintof** [comment]
Люди с снс собрались чтобы дружно апнуть квешен, уже поздно, но + up

**Comment by Faintof** [comment]
хуй

**Pull request merged**
