### PR TITLE
check for an outofbounds exception from getSection

### PR DESCRIPTION
**Pull request by RealGatt**
Duplicate of #552 due to me doing a boo-boo and making this change in my primary 1.18 branch 🙃 

See the original ticket for explanation/etc (apologies)

### CODE REVIEW

**Comment by TheMode** [comment]
I still do not believe it to be a proper fix, we are increasing the risk of people modifying the section without understanding that it is a placeholder for "not present". Not to mention initialization cost.

**Comment by Kebab11noel** [comment]
You should find the root cause of the issue instead of making a change which just makes it fail silently, it's the caller's responsibility to not request a section outside of the world.

**Comment by RealGatt** [comment]
Looking into the root cause of the issue now. Keeping this open (unless you want it closed) so I remnember to work on this branch more

**Comment by RealGatt** [comment]
Issue has been resolved w/ latest /1.18 commits

**Pull request closed without merging**
