### PR TITLE
Resetting player flying speed after changing gamemode

### PR DESCRIPTION
**Pull request by Pelfox**
Hello. Today I found a bug, that causes the player not to reset flying speed after changing the gamemode. So, I decided to fix it.

### CODE REVIEW

**Comment by TheMode** [comment]
Could you test it? In this case I assume in https://github.com/Minestom/Minestom/blob/master/src/test/java/net/minestom/server/entity/player/PlayerIntegrationTest.java#L30

**Comment by Pelfox** [comment]
This there any CONTRIBUTING.md or something like this? I don't know how to test it. Will something like
```java
        player.setGameMode(GameMode.SPECTATOR);
        player.setFlyingSpeed(1.0f);
        player.setGameMode(GameMode.CREATIVE);
        assertEquals(player.getFlyingSpeed(), 0.05f);
```
good?

**Comment by TheMode** [comment]
Those are normal junit tests - but with a small API to retrieve game objects.

The general idea is to add tests that fail on master, but that your changes fix. It has the advantages of:
- Properly explaining what you are fixing
- Ensure that future contributors do not break those changes without knowing

**Comment by Pelfox** [comment]
So, this RP does nothing (as I and Moulberry saw on his stream), so I'll close it

**Pull request closed without merging**
