### PR TITLE
Fix Lighting Invalidation

### PR DESCRIPTION
**Pull request by iam4722202468**
- Fix invalid lighting being sent to clients
- Add cherry leaves to occludes
- Fix lighting being generated when using loaded lighting
- Send lighting to clients on block changes
- Cleanup unused methods
- Add sky lighting test for short grass

### CODE REVIEW

**Comment by iam4722202468** [comment]
I would be surprised if there were lighting bugs found after this PR

**Review by reosfire — CHANGES_REQUESTED** [review]
```java
Random rnd = new Random();
instanceContainer.setGenerator(unit -> {
  if (rnd.nextBoolean()) {
    unit.modifier().fillHeight(0, 40, Block.STONE);
  }

  if (rnd.nextBoolean() && unit.absoluteStart().blockY() < 40 && unit.absoluteEnd().blockY() > 40) {
    unit.modifier().setBlock(unit.absoluteStart().blockX(), 40, unit.absoluteStart().blockZ(), Block.GLOWSTONE);
  }
  if (rnd.nextBoolean() && unit.absoluteStart().blockY() < 50 && unit.absoluteEnd().blockY() > 50) {
    unit.modifier().setBlock(unit.absoluteStart().blockX() + 6, 50, unit.absoluteStart().blockZ() + 6, Block.STONE);
  }
});
```

With this generator light breaks like this image

**Comment by iam4722202468** [comment]
@reosfire thanks, should be fixed now

**Review by txfsjyqm — APPROVED** [review]

**Comment by reosfire** [comment]
> @reosfire thanks, should be fixed now
Now it looks pretty good. RIP my week trying to build lighting from scratch :(

**Review by reosfire — APPROVED** [review]

**Pull request merged**
