### PR TITLE
Randomize sound seed in AdventurePacketConvertor

### PR DESCRIPTION
**Pull request by Am-Gone**
Fix for #1594

### CODE REVIEW

**Comment by NitrinCloud** [comment]
Great initial idea, but when we just randomize the sound we can't decide which sound to use. You should consider using the seed provided by the given sound and in my opinion, if it isn't given, you should randomize it.

For example like so...
```java 
sound.seed().orElse(SOUND_SEED_RANDOM.nextLong())
```

**Comment by Am-Gone** [comment]
In my opinion this is a pretty bad idea as this is a seed, not the actual played value. Also, if you really want to use a specific seed, you can still create the packet yourself.

**Comment by NitrinCloud** [comment]
From what I know, every sound in minecraft has a spefic seed and the seed which is send to the client will then be translated to the nearest seed from the sound.

It would be unecessary to create your own paket since the seed would be just optional. Since you can specify the seed for the sound, everyone would exspect (as default behaviour) the seed to be the same as specified.

**Comment by Am-Gone** [comment]
That is not what I found... For me, the seed only helps determining which sound file must be used. Also, the original vanilla code always use the level random source.

**Comment by NitrinCloud** [comment]
Take a look at [this](https://github.com/Owen1212055/mc-sound-seeds) repository. If the client would randomize the sound anyway, you didn't even have to send a random seed

**Comment by Am-Gone** [comment]
Well yes this is 

> In my opinion this is a pretty bad idea as this is a seed, not the actual played value. Also, if you really want to use a specific seed, you can still create the packet yourself.

I still think that it should stay like this. What you've sent is a compilation of seeds that were manually found that plays a specific sounds and is a very specific use-case. Also, this is not version consistent and you can't pull this kind of data off the registry, which means no data generator.

**Comment by NitrinCloud** [comment]
Even tho you are right, there is no real downside in using the provided seed if specified. Like I said, most users will assume that this is the case

**Comment by hapily04** [comment]
Completed [here](https://github.com/hollow-cube/minestom-ce/pull/74) and was merged into this repo with the Minestom-ce -> Minestom massive merge

**Pull request closed without merging**
