### PR TITLE
Refactor while we still can

### PR DESCRIPTION
**Pull request by xt449**
Refactored all "Instance" classes to "World".

Moved net.minestom.server.instance.block to net.minestom.server.block
Moved net.minestom.server.instance to net.minestom.server.world

Refactored most if not all relevant fields, variables, methods, and Javadocs referencing Instance objects to now reference there respective World objects

EDIT:
Also replaced ambiguous Javadocs containing "... for instance ..." with "... for example ..."

### CODE REVIEW

**Comment by xt449** [comment]
Resolves #314

**Review by kezz — CHANGES_REQUESTED** [review]
I'm against this PR and the changes it makes. Both because `World` is, in my opinion, worse than `Instance` but also I think such a change would be better suited for a 1.0 to 2.0 version bump.

**Comment by xt449** [comment]
Missing instance of instanced instance from instance manager: no instances found in Minestom instance of instances manager (for instance SharedInstance).

**Comment by LeoDog896** [comment]
I also agree with @kezz on this one -- Instance is definitely not the best name, but I definitely do not think World is a better replacement.

**Pull request closed without merging**
