### PR TITLE
Fixed switching slots while using item

### PR DESCRIPTION
**Pull request by Lukadcf**
Before:

https://github.com/user-attachments/assets/94b39c7e-6bf8-449a-9eac-e4a93d5fb7b8

After:

https://github.com/user-attachments/assets/e29f1892-2328-474d-8bae-695d5f96a2d4

### CODE REVIEW

**Comment by Lukadcf** [comment]
Just realized I added this check twice, so if someone can remove that or teach me how to edit a pr that'd be great

```java
boolean usingMainHand = player.getItemUseHand() == Player.Hand.MAIN && hand == Player.Hand.OFF; //<- remove
PlayerUseItemEvent useItemEvent = new PlayerUseItemEvent(player, hand, itemStack, player.getItemUseHand() == Player.Hand.MAIN && hand == Player.Hand.OFF ? 0 : defaultUseItemTime(itemStack));```

**Comment by GreatWyrm** [comment]
@Lukadcf You can commit to the same branch (lukadcf-patch-itemUse) again to fix it

**Comment by Lukadcf** [comment]
> @Lukadcf You can commit to the same branch (lukadcf-patch-itemUse) again to fix it
Thank you, I fixed it 👍

**Comment by mworzala** [comment]
Nice, thanks for the fix!

**Pull request merged**
