### PR TITLE
1.19.3 support

### PR DESCRIPTION
**Pull request by TheMode**

### CODE REVIEW

**Comment by MenschenToaster** [comment]
Any updates on this?

**Comment by SteinGaming** [comment]
There is an issue when using 0488915fdaff4b51c4375da27be2dcf79215435d (from JitPack), which causes materials from items not being sent correctly. 

While Minestom says the item is Material.COMPASS, the client has a Material.SLIME_BALL (maybe shows that the id moved 2 to the back (from 833, the compass id, to 831, the slime ball id), didn't test much more than this)

The issue isn't present in the 1.19 branch, and I confirmed that the issue isn't due to the proxy or it's plugins.
I also confirmed that the Material is set correctly using the Remote JVM debugger, which showed that the item itself and in the players inventory was set to COMPASS.

**Comment by TheMode** [comment]
We need to update our data generator https://github.com/Minestom/MinestomDataGenerator/tree/1.19.3 which hasn't been done yet due to some api changes

**Comment by SquaredStudios-MC** [comment]
Any updates?

**Comment by MenschenToaster** [comment]
> Any updates?

The Branch is stable for the stuff I use minestom for. 
I'm worried, that it will take them as long as this for 1.19.4 tho :/

**Comment by CodeDoctorDE** [comment]
I think this can be closed by #1851?

**Comment by mworzala** [comment]
Done in #1851

**Pull request closed without merging**
