### PR TITLE
use kotlin

### PR DESCRIPTION
**Pull request by LeoDog896**
As every contributor agreed, kotlin is very good. Some statements from the team:

"kotlin" - me
"I love kotlin" - me
"kotlin" - part of quote by mattw

and more.

We all <3 kotlin!

### CODE REVIEW

**Comment by GoldenStack** [comment]
Not enough COBOL, please come back later.

**Comment by GoldenStack** [comment]
👎 Needs more BASIC

**Comment by LeoDog896** [comment]
kotlin is very basic :+1:

**Comment by iam4722202468** [comment]
Looks good. Do you have a timeframe for when this will get merged in to master?

**Comment by LeoDog896** [comment]
> Looks good. Do you have a timeframe for when this will get merged in to master?

Once the kotlin team adds the `condition Leo statement LeoLeo statement` for the Leo (ternary) operator, we'll be good to go.

**Review by TheMode — APPROVED** [review]
LGTM

**Comment by GoldenStack** [comment]
You have still not added any COBOL.

**Comment by LeoDog896** [comment]
COBOL is outdated. Long live BASIC, the best language.

**Comment by Peter-Crawley** [comment]
As a Kotlin user, I approve of this. *I am not joking.*

**Review by BomBardyGamer — APPROVED** [review]
Brilliant. Sorry I'm a bit late.

**Review by dev-hydrogen — CHANGES_REQUESTED** [review]
LBTM, Use PHP instead?

**Comment by KrystilizeNevaDies** [comment]
Closed in favor of clojure port.

**Comment by iam4722202468** [comment]
Can we get an update on this

**Comment by emortaldev** [comment]
> Can we get an update on this
Too much Kotlin

**Comment by LeoDog896** [comment]
We should have ported it to Scala, obviously.

**Comment by GoldenStack** [comment]
Does this need a second look?

**Comment by Codestech1** [comment]
Assembler when?

**Pull request closed without merging**
