### PR TITLE
Add Potion flags

### PR DESCRIPTION
**Pull request by MrGazdag**
Adds the flags used in the `flags` parameter of the constructor and the byte returned by `flags()`.
This PR also includes a bit of documentation.

### CODE REVIEW

**Comment by mworzala** [comment]
I would prefer to have methods such as `isAmbient`, `hasParticles`, etc instead of exposing the flags field directly

**Comment by MrGazdag** [comment]
> I would prefer to have methods such as `isAmbient`, `hasParticles`, etc instead of exposing the flags field directly

Honestly i would prefer both, i'm going to add the methods

**Comment by mworzala** [comment]
Not sure what I was talking about, its a record we can't not have the `flags` method

**Comment by MrGazdag** [comment]
> Not sure what I was talking about, its a record we can't not have the `flags` method

We can have methods to query the individual flag values though

**Review by mworzala — APPROVED** [review]

**Pull request merged**
