### PR TITLE
1.21.2 & 1.21.3

### PR DESCRIPTION
**Pull request by mworzala**
Working branch for supporting the 1.21.2 (and 1.21.3, they are the same protocol) update.

This branch is not 100% complete, so expect bugs. Known missing work is marked with `TODO(1.21.2)` in the codebase. However it is at a point where it should be usable for most people. If you encounter bugs, please report them! 

There are some breaking changes from the `next` branch included in this update. There is not yet an update guide, however that will come before a final release of this branch. You have been warned :)

As usual, you can import snapshots of this branch using the following maven coordinates: `net.minestom:minestom-snapshots:1_21_2-<first 10 digits of a commit hash>`. The first published hash will be `ee6a7180b4`.

Thanks all!

### CODE REVIEW

**Comment by mworzala** [comment]
Note for myself: include https://github.com/Minestom/Minestom/pull/2340

**Comment by KermanIsPretty** [comment]
What about including #2302 as it seems like now is the only good time to merge this in or start the deprecation for the permission API. As permissions should be handled by whatever player/entity implementation you use.

**Comment by CryptForge** [comment]
The `ClientSteerVehiclePacket` packet is now always sent, even when you're not in a vehicle, so I think the naming should be changed there.

**Comment by MelonHell** [comment]
> What about including #2302 as it seems like now is the only good time to merge this in or start the deprecation for the permission API. As permissions should be handled by whatever player/entity implementation you use.

I updated the PR, I hope it will be accepted :D

**Comment by mudkipdev** [comment]
Permission related issues that should be closed:
https://github.com/Minestom/Minestom/pull/984
https://github.com/Minestom/Minestom/pull/1474
https://github.com/Minestom/Minestom/pull/1610
https://github.com/Minestom/Minestom/issues/2021
https://github.com/Minestom/Minestom/pull/2023

**Comment by mworzala** [comment]
Here is the current version of the update notes: https://gist.github.com/mworzala/69eb0a3e16b74b5a4959c69d82b70264

The following issues need to be resolved before this branch is merged:
* https://github.com/Minestom/Minestom/issues/2496
* https://github.com/Minestom/Minestom/issues/2475
* https://github.com/Minestom/Minestom/issues/2480

This is expected to be merged before 1.21.4 comes out on Tuesday Dec 3

**Pull request merged**
