### PR TITLE
Permissions rework 

### LINKED ISSUE #2021: Rework the permission system
Problems:
- There is no way to replace a player's PermissionHandler without extending Player class
- The net.minestom.server.permission.Permission class is useless
- No tristate system (True/False/Undefined)

### PR DESCRIPTION
**Pull request by MelonHell**
resolves #2021

### CODE REVIEW

**Review by LooFifteen — APPROVED** [review]
lgtm

**Comment by MelonHell** [comment]
Why do entities need permissions? It seems to me that they are only needed by CommandSender

**Comment by MelonHell** [comment]
_TODO rename Permissions back to PermissionHandler and add a setter_

**Comment by MelonHell** [comment]
Permissions removed in https://github.com/Minestom/Minestom/pull/2445

**Pull request closed without merging**
