### PR TITLE
Rename Effects to World Events, update world event list

### PR DESCRIPTION
**Pull request by GreatWyrm**
Rename Effects to World Events to align with https://wiki.vg/Protocol#World_Event
Update list of World Events to match wiki.vg

### CODE REVIEW

**Comment by mudkipdev** [comment]
I think we should follow the naming conventions of mojang, but the naming is the same in this case (`LevelEvent` vs `WorldEvent`)

**Comment by mworzala** [comment]
The events and their IDs seem like they should be generated to me if its reasonable.

**Comment by GreatWyrm** [comment]
I agree, I think they should be generated.
I did take a look and I unfortunately could not find an easy way to generate them.

**Comment by mworzala** [comment]
Here you go! :) https://github.com/Minestom/MinestomDataGenerator/pull/36

**Comment by GreatWyrm** [comment]
Whoa, appreciate it! Once that's merged and the data gen version is bumped, I can add that to the auto-generated data.

**Comment by GreatWyrm** [comment]
Superseded by #2499.

**Pull request closed without merging**
