### PR TITLE
(WIP) Rework StairsPlacementRule

### PR DESCRIPTION
**Pull request by alexwith**
This is a cleanup and simplified version of the StairsPlacementRule. The missing part is updating the surrounding stairs on block place.

### CODE REVIEW

**Comment by mworzala** [comment]
I feel like im having memory loss, I thought I commented here earlier.

You should add this to `com.minestom.extras.PlacementRules`.

**Comment by alexwith** [comment]
> I feel like im having memory loss, I thought I commented here earlier.
> 
> You should add this to `com.minestom.extras.PlacementRules`.

There are so many types of stairs, we need a better system.

**Comment by mworzala** [comment]
Open to alternatives.

**Comment by mworzala** [comment]
Closing this for now as it is quite old, happy to look again if a version is updated and added to `PlacementRules`.

**Pull request closed without merging**
