### PR TITLE
Resetting player flying speed after changing gamemode

### PR DESCRIPTION
**Pull request by Pelfox**
Hi. This is an improved version of my PR #707. This PR contains a fix, that resets the player's speed after changing the gamemode.

### CODE REVIEW

**Comment by Moulberry** [comment]
Make sure to check `isActive()` so that you don't send the packet if the player isn't in the PLAY state

**Comment by TheMode** [comment]
Would be worth an explanatory comment

**Comment by TheMode** [comment]
I was mostly referring to `!isActive()` as it does not make a ton of sense to me.

**Comment by Pelfox** [comment]
OMG, I’m so stupid. Sorry

**Comment by TheMode** [comment]
No problem!

And you generally want comments to either explain the unsaid, or ease the reading. In this case it could be (given as example) `Sync abilities with the client to avoid X issue, we must therefore also ensure that the modified abilities are correct)`

**Pull request merged**
