### PR TITLE
Add ability to get Block type from given position

### PR DESCRIPTION
**Pull request by iamceph**
A little nice to have shortcut in the Instance & Chunk API :)

### CODE REVIEW

**Comment by KrystilizeNevaDies** [comment]
I think it would be a better idea to omit this from Chunk and only have it in Instance, the idea being that chunk deals with the actual short array while instance can have this method as a shorthand, will have to check with other contributors though.

**Comment by iamceph** [comment]
I get what are you saying here but it is basically the same method as getBlockStateId(). I'd say that you are right, I just wanted to add ability to getBlock too, as in BlockModifier you can do setBlock and I ended up in adding it into the Chunk too 😅 I can make the changes if needed.

**Comment by KrystilizeNevaDies** [comment]
Will have to see what TheMode says

**Comment by KrystilizeNevaDies** [comment]
Talked with TheMode and he also thinks that the getblock method should be only in instance. If you'd like to just change that, I'll merge, if not, I'll do it myself.

**Comment by iamceph** [comment]
Fixed :)

**Pull request merged**
