### PR TITLE
Entity#getUniqueId

### PR DESCRIPTION
**Pull request by NelminDev**
Hello,
I am an old Spigot Dev and I wondered where Player#getUniqueId went then I saw it's Player#getUuid and I thoughtt I can change it :)

PS: I didn't remove getUuid()

### CODE REVIEW

**Comment by ZakShearman** [comment]
Both methods shouldn't exist - a decision should be made on what naming scheme should be used and the old one deprecated.

**Review by Tjorven-Liebe — APPROVED** [review]

**Comment by mworzala** [comment]
It seems like an unnecessary breaking change to me.

**Comment by NelminDev** [comment]
Why breaking?

**Comment by mworzala** [comment]
Sorry, I should have clarified. I agree with Zak that there should not be both of them, and removing `getUuid` will be a breaking change.

**Comment by FlorianMichael** [comment]
There is no reason to change the name of the method so randomly, it will only unnecessarily break API that the method was using, such changes should only be done with major updates where API is definitely changed

**Comment by KrystilizeNevaDies** [comment]
I will close this pr for now since the consensus is that we don't want to change the api without a good reason, and being consistent with spigot isn't a good enough reason for us.

**Pull request closed without merging**
