### PR TITLE
Make the start log use BrandName instead of hardcoded "Minestom"

### PR DESCRIPTION
**Pull request by TomJuri**

### CODE REVIEW

**Comment by TomJuri** [comment]
Weird these tests fail even without modified code...

**Comment by GreatWyrm** [comment]
The test this PR failed on is particularly flaky for some unknown reason, I've seen it fail on my PRs, and when the test was run again, it passed.

**Comment by TomJuri** [comment]
Can I re run the tests?

**Comment by TomJuri** [comment]
There we go

**Pull request merged**
